version : '3'
services:
  mqs1:
    container_name: MQS1
    build: ./MQS1
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=EARTH
      - MQ_APP_PASSWORD=abcd
    ports:
      - "1414:1414"
      - "9443:9443"
    networks:
      - mq-remote-network
  mqs2:
    container_name: MQS2
    build: ./MQS2
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=MOON
      - MQ_APP_PASSWORD=abcd
    ports:
      - "1415:1414"
      - "9444:9443"
    networks:
      - mq-remote-network
networks: 
  mq-remote-network: 